# See: https://github.com/mkdocs/mkdocs/blob/master/docs/user-guide/configuration.md
site_name: Social Media API
site_description: Sample Social Media API Description.
site_author: Shubham Mishra
repo_url: https://github.com/subhmmisra/social_media

nav:
- Home: index.md

- API:
  - 'Overview': api/0-overview.md
  - 'Friends/Friends List': api/1-friends.md

- Backend:
  - 'Coding Rules': backend/coding_rules.md
- Release Notes: release_notes.md